### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified: '.'

### ISSUE THREAD

**Issue by evandrocoan** [DavidGerva/AddFolderToProject-SublimePlugin#3]
```
Traceback (most recent call last):
  File "F:\SublimeText\sublime_plugin.py", line 935, in is_visible_
    ret = self.is_visible()
  File "F:\SublimeText\Data\Packages\AddFolderToProject\AddFolderToProject.py", line 98, in is_visible
    if (filePath and AddFolder.exists(self, os.path.dirname(filePath) ) ):
  File "F:\SublimeText\Data\Packages\AddFolderToProject\AddFolderToProject.py", line 26, in exists
    if os.path.samefile( dirPath, folder['path']):
  File "./python3.3/ntpath.py", line 603, in samefile
FileNotFoundError: [WinError 2] The system cannot find the file specified: '.'
```

Happens when I have this project file:
```
{
    "folders":
    [
        {
            "path": "."
        },
    ]
}
```

**Comment by evandrocoan** [comment]
Duplicate of: https://github.com/DavidGerva/AddFolderToProject-SublimePlugin/issues/2
